### ISSUE TITLE
Could you share your config file as a example?

### ISSUE THREAD

**Issue by youngwanLEE** [sxhxliang/detectron2_backbone#3]
Hi,

I'm impressed by your work.

Could you share your full EfficientDet config file as an example? 

Recently, I also implemented bifpn with vovnet but the model result is not as good as the fpn-one. 

I expect the reason that is related to the normalization in the bifpn (I tested GN, BN, and SyncBN).

**Comment by sxhxliang** [comment]
sorry for the late reply, bifpn in this repo is not as good as the fpn,  but the backbone efficientnet works well.

**Comment by youngwanLEE** [comment]
Thanks
